const characterSort = {
	extra_tw: ["tw_shen_guanyu", "tw_shen_lvmeng"],
	tw_sp: ["tw_zhenji", "tw_yj_fazheng", "tw_zhangyun", "tw_simashi", "tw_qiaozhou", "old_jiakui", "tw_jsp_guanyu", "tw_mazhong", "simafu", "tw_fuwan", "tw_yujin", "tw_zhaoxiang", "tw_hucheer", "tw_mayunlu", "tw_re_caohong", "tw_furong", "tw_yangyi", "tw_daxiaoqiao", "tw_dengzhi", "tw_fanchou", "tw_haomeng", "tw_qiaorui", "tw_weixu", "tw_dengzhi", "tw_yangyi", "tw_baosanniang"],
	tw_canghai_gui: ["tw_liuhong", "tw_hejin", "tw_caozhao", "tw_yuantan", "tw_wangchang"],
	tw_canghai_zun: ["tw_zhanghong", "tw_zhangzhao", "tw_zhangji", "tw_tianyu", "tw_jiangji"],
	tw_canghai_ye: ["tw_gexuan", "tw_zhugejun", "tw_bingyuan"],
	tw_canghai_jie: ["tw_zhangmancheng", "tw_yufuluo", "duosidawang", "tw_zangba"],
	tw_canghai_xiang: ["tw_liufuren", "tw_zhangning"],
	tw_canghai_ge: ["tw_yanliang", "tw_wenchou", "tw_jiling", "tw_mateng", "tw_baoxin", "tw_xiahoushang", "tw_niujin", "wuban"],
	tw_canghai_fu: ["tw_dongzhao", "jiachong", "tw_xiahouen", "tw_yanxiang", "tw_puyangxing", "tw_liwei"],
	tw_canghai_san: ["tw_gongsunfan", "tw_yangang", "tw_niufudongxie", "tw_jianshuo", "tw_huchuquan", "yuejiu"],
	tw_canghai_yi: ["licuilianzhaoquanding"],
	tw_canghai_sha: ["tw_huojun", "tw_zhangnan", "tw_fengxí"],
	tw_yunchouzhi: ["tw_wangcan", "tw_bianfuren", "tw_feiyi", "tw_chenzhen", "tw_xunchen"],
	tw_yunchouxin: ["tw_wangling", "tw_wujing", "tw_zhouchu"],
	tw_yunchouren: ["tw_liuzhang", "tw_xujing", "tw_qiaogong"],
	tw_yunchouyong: ["tw_zongyu", "tw_chendong", "tw_sunyi"],
	tw_yunchouyan: ["tw_jiangqing", "tw_huangfusong"],
	tw_sbcharacter: ["tw_sb_sp_zhugeliang", "tw_sb_caopi", "tw_sb_xiahoudun", "tw_sb_yl_luzhi"],
	tw_bingshi: ["tw_pot_huanjie"],
	tw_swordsman: ["xia_yuzhenzi", "xia_shie", "xia_shitao", "xia_guanyu", "xia_liubei", "xia_xiahousone", "xia_xiahoudun", "xia_zhangwei", "xia_xushu", "xia_wangyue", "xia_liyàn", "xia_tongyuan", "xia_lusu", "xia_dianwei", "xia_zhaoe", "xia_xiahouzie"],
	tw_beiding: ["huan_luxun", "huan_liushan", "huan_zhugeliang", "huan_jiangwei", "huan_zhanghe", "huan_zhugeguo", "huan_weiyan", "huan_simayi", "huan_zhaoyun"],
	tw_weiang: ["huan_liufeng", "huan_caoang", "huan_huanggai", "huan_dingshangwan", "huan_dianwei", "huan_caopi", "huan_caozhi", "huan_caochong"],
	tw_bawang: ["huan_sunce", "huan_daqiao", "huan_zhouyu", "huan_xiaoqiao", "huan_fazheng"],
	tw_jsrg: ["tw_jsrg_wangyun", "tw_jsrg_hejin", "tw_jsrg_caocao", "tw_jsrg_huangfusong", "tw_jsrg_sunjian", "tw_jsrg_liubei"],
	tw_mobile: ["nashime", "tw_lingju", "tw_beimihu", "tw_zhugeguo", "tw_yj_zhanghe"],
	tw_standard: ["tw_zhangfei"],
	tw_shenhua_yin: ["tw_yl_luzhi"],
	tw_shenhua_lei: ["tw_guanqiujian"],
	tw_yijiang1: ["tw_re_fazheng"],
	tw_yijiang2: ["tw_chengpu", "tw_madai", "tw_handang"],
	tw_yijiang3: ["tw_fuhuanghou", "tw_guohuai"],
	tw_yijiang4: ["tw_sunluban", "tw_guyong", "tw_jushou"],
	tw_yijiang5: ["tw_zhuzhi", "tw_caoxiu", "old_quancong"],
	tw_yijiang7: ["tw_xuezong"],
	tw_yijiang: ["tw_caoang", "tw_caohong", "tw_zumao", "tw_dingfeng", "tw_maliang", "tw_xiahouba"],
	tw_english: ["kaisa"],
	tw_sxrm: ["tw_sxrm_huatuo", "tw_sxrm_liubei", "tw_sxrm_caocao", "tw_sxrm_fuhuanghou"],
	tw_waitingforsort: [],
};

const characterSortTranslate = {
	tw_sp: "海外服·SP",
	tw_canghai_gui: "沧海遗珠·天潢贵胄",
	tw_canghai_zun: "沧海遗珠·折冲樽俎",
	tw_canghai_ye: "沧海遗珠·孤鸿翔野",
	tw_canghai_jie: "沧海遗珠·草莽豪杰",
	tw_canghai_xiang: "沧海遗珠·瘗玉埋香",
	tw_canghai_ge: "沧海遗珠·金戈铁马",
	tw_canghai_fu: "沧海遗珠·附骥攀鳞",
	tw_canghai_san: "沧海遗珠·鸦军散勇",
	tw_canghai_yi: "沧海遗珠·遗珠拾贝",
	tw_canghai_sha: "沧海遗珠·沙场点兵",
	tw_mobile: "海外服·稀有专属",
	tw_yunchouzhi: "运筹帷幄·智",
	tw_yunchouxin: "运筹帷幄·信",
	tw_yunchouren: "运筹帷幄·仁",
	tw_yunchouyong: "运筹帷幄·勇",
	tw_yunchouyan: "运筹帷幄·严",
	tw_sbcharacter: "海外服·谋攻篇",
	tw_bingshi: "海外服·兵势篇",
	tw_swordsman: "海外服·武侠篇",
	tw_beiding: "海外服·北定中原",
	tw_weiang: "海外服·魏昂龙兴",
	tw_bawang: "海外服·霸王问鼎",
	tw_jsrg: "海外服·江山如故",
	tw_standard: "海外服异构·标准包",
	tw_shenhua_yin: "海外服异构·难知如阴",
	tw_shenhua_lei: "海外服异构·动如雷霆",
	tw_yijiang1: "海外服异构·将1",
	tw_yijiang2: "海外服异构·将2",
	tw_yijiang3: "海外服异构·将3",
	tw_yijiang4: "海外服异构·将4",
	tw_yijiang5: "海外服异构·将5",
	tw_yijiang7: "海外服异构·原7",
	tw_yijiang: "一将成名TW",
	tw_english: "英文版",
	tw_waitingforsort: "等待分包",
	extra_tw: "海外服异构·神将",
	tw_sxrm: "海外服·蚀心入魔",
};

export { characterSort, characterSortTranslate };
